coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 0
        if_ci_failed: error
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
      - type: patch
  individual_components:
    - component_id: stealcell
      paths:
        - crates/stealcell/**
